### ISSUE TITLE
How to pass a multiple arguments to my function?

### ISSUE THREAD

**Issue by lkjhgfda** [Tyler-Hardin/thread_pool#4]
I tried something like
```c++
...
int myFunc(int a, int b, int c)
...
... myPool.async(std::function<int(int, int, int)>(myFunc), a, b, c)...
```
and get a ton of errors.
But if I using function with 1 argument everything works well.
What i'm doing wrong?

**Comment by Tyler-Hardin** [comment]
It might help if you paste the errors and a larger section of the code.

**Comment by Tyler-Hardin** [comment]
It was a bug. I think it's fixed. Let me know if you're still getting errors.
