### ISSUE TITLE
Test as number of threads decreased : infinite loop?

### ISSUE THREAD

**Issue by pocdn** [Tyler-Hardin/thread_pool#5]
I simplified the original test code to be the following

[test.cpp.gz](https://github.com/Tyler-Hardin/thread_pool/files/1096524/test.cpp.gz)

`#include "thread_pool.hpp"
#include \<vector\>
#include \<iostream\>     // std::cout, std::endl 
using namespace std;

/*
 * Intel Xeon ES-1620 v3 3.5GHz
 * 
 * git clone https://github.com/Tyler-Hardin/thread_pool.git
 * git checkout -b cv origin/cv
 *
 * $ gcc --version
 * gcc.exe (Rev3, Built by MSYS2 project) 6.3.0
 * $ g++ --std=c++11 test.cpp thread_pool.cpp
 * $ time ./a.exe
 * ...
 * 
 * real   5m23.883s for num_threads = 1 (aborted manually)
 * real   3m55.198s for num_threads = 2 (aborted manually)
 *   why do above configurations never finish but the ones below do finish?
 *   Further, if add "-O3" to compiler option above, the run in 26s and 13s,why?
 * real   0m12.690s for num_threads = 3
 * real    0m9.199s for num_threads = 4
 * real    0m7.971s for num_threads = 5
 * real    0m7.654s for num_threads = 6
 * real    0m7.304s for num_threads = 7
 * real    0m7.740s for num_threads = 8
*/

bool func_bool_int(int n) {
	if(n < 2)
		return false;
	for(int i = 2;i < n;i++)
		if(n % i == 0)
			return false;
	return true;
}

int main() {

  const int num_threads = 4;
	thread_pool p(num_threads);

	int n = 100000;
	int max = 5 * n;
	vector<future<bool>> f;
	for( int i = n; i < max; i++ )
		f.emplace_back(p.async(function<bool(int)>(func_bool_int), i));

  std::cout << "..." << std::endl;
  size_t accum = 0;
	for(auto &i : f) {
    accum += i.get();
  }
  std::cout << "accum = " << accum << std::endl;

	return 0;
}
`

When I ran for num_threads = 8, 7, 6, 5, 4, 3 things went okay. But when I tried num_threads of 2 or 1 the runtime seemed to be in an infinite loop ie I was seeing about 7s to 12s runtimes above num_threads>2 but once I tried num_threads=2 or 1 I waited 3 minutes to 5 minutes (orders of magnitude longer than extrapolated runtime) before manually killing the process. Is this behavior to be expected? Note this was on a gcc 6.3 with "git checkout -b cv origin/cv" branch.  Adding an "-O3" optimazation seemed to fix the issue; expected?

**Comment by Tyler-Hardin** [comment]
Not expected, but the cv branch hasn't been tested or used at all, afaik.
Does the issue exist in master?

**Comment by pocdn** [comment]
I was able to compile on Windows and successfully run with
 gcc.exe (Rev3, Built by MSYS2 project) 6.3.0
only with the older ThreadPool revision 65879c9 since I didn't have the latest gcc comipler collection installed.

But on Ubuntu with the master revision using
g++-7 (Ubuntu 7.1.0-5ubuntu2~16.04) 7.1.0
ie g++-7 -std=c++17 -fconcepts test.cpp thread_pool.cpp -pthread
all worked fine.

It was my fault in using the cv branch originally. 

Thanks

**Comment by Tyler-Hardin** [comment]
No problem. Glad to have people making use of my code.

**Comment by pocdn** [comment]
It's been helpful code. Thanks for sharing your work and efforts.
